name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.wolfiz.org
          username: ${{secrets.githubtest@wolfiz.org}}
          password: ${{secrets. admin123!@# }}
          server-dir: /
